/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaznica;
import javax.swing.JFrame;

import dialogy.NovaVeznicaDialog;
import java.util.HashMap;
import vaznica.Cela;
import vaznica.MunicnySklad;
import vaznica.StraznaVeza;
import vaznica.objektyvaznice.Straznik;
import dialogy.ZamestnajStraznikaDialog;
import java.util.logging.Level;
import java.util.logging.Logger;
import vaznica.objektyvaznice.Hodnost;
import vaznica.objektyvaznice.TypZamestnania;
import vynimky.ZamestnanieZamestnancaException;
import vaznica.objektyvaznice.Vrah;
import dialogy.UvezniVrahaDialog;
import vaznica.objektyvaznice.StupenNebezpecenstva;
import vynimky.UveznenieVeznaException;
import dialogy.UvezniBankovehoLupicaDialog;
import vaznica.objektyvaznice.BankovyLupic;
import vaznica.objektyvaznice.Lekar;
import dialogy.ZamestnajLekaraDialog;
import vaznica.objektyvaznice.Granat;
import dialogy.VlozGranatDialog;
import vynimky.VlozenieVyzbrojeException;
import dialogy.VlozSamopalDialog;
import vaznica.objektyvaznice.Samopal;
import dialogy.PrepustiZamestnancaDialog;
import vynimky.PrepustenieZamestnancaException;
import dialogy.PrepustiVeznaDialog;
import vynimky.PrepustenieVeznaException;
import dialogy.OdoberVyzbrojDialog;
import vynimky.OdobratieVyzbrojeException;
import dialogy.PracujBankovyLupicDialog;
import javax.swing.JOptionPane;
import dialogy.UlozDoSuboruDialog;
import vaznica.objektyvaznice.IUveznitelny;
import dialogy.OstetriOsobyDialog;
import vaznica.objektyvaznice.IZamestnatelny;
import dialogy.PocOdpracovanychHodStraznikDialog;
import vaznica.Veznica;

/**
 * Trieda predstavuje graficke rozhranie programu 
 * @author Dominik Vrbovsky
 */
public class GUIAplikacia extends javax.swing.JFrame {
    private JFrame aplikacia;
    private Cela cela;
    private StraznaVeza straznaVeza;
    private MunicnySklad municnySklad;
    private Straznik straznik;
    private Vrah vrah;
    private BankovyLupic bankovyLupic;
    private Lekar lekar;
    private Granat granat;
    private Samopal samopal;
    private Veznica veznica;
    
    
    /**
     * Creates new form GUIAplikacia
     */
    public GUIAplikacia() {
        initComponents();
        this.aplikacia = this;
        this.cela = null;
        this.straznaVeza = null;
        this.municnySklad = null;
        this.straznik = null;
        this.jmZamestnaj.setEnabled(false);
        this.jmVyzbroj.setEnabled(false);
        this.jmVezen.setEnabled(false);
        this.jmUlozDoSuboru.setEnabled(false);
        this.vrah = null;
        this.bankovyLupic = null;
        this.lekar = null;
        this.granat = null;
        this.samopal = null;
        this.veznica = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpStavVeznice = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmivVytvorVeznicu = new javax.swing.JMenuItem();
        jmiKoniec = new javax.swing.JMenuItem();
        jmZamestnaj = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jmiZamestnajStraznika = new javax.swing.JMenuItem();
        jmiZamestnajLekar = new javax.swing.JMenuItem();
        jmiPrepustiZam = new javax.swing.JMenuItem();
        jmiOsetriOsoby = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiOdpracujStraznik = new javax.swing.JMenuItem();
        jmVezen = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jmiUvezniVraha = new javax.swing.JMenuItem();
        jmiUvezniBankLu = new javax.swing.JMenuItem();
        jmiPrepustiVezna = new javax.swing.JMenuItem();
        jmiZnizStupenNeb = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiPracujBanLup = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jmiBitkaSoStraz = new javax.swing.JMenuItem();
        jmiPridajnavsVrah = new javax.swing.JMenuItem();
        jmiPrijminav = new javax.swing.JMenuItem();
        jmVyzbroj = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jmiVlozgranat = new javax.swing.JMenuItem();
        jmiVlozSamopal = new javax.swing.JMenuItem();
        jmiOdoberZMunSkl = new javax.swing.JMenuItem();
        jmUlozDoSuboru = new javax.swing.JMenu();
        jmiUlozCislaNeb = new javax.swing.JMenuItem();
        jmiUlozCisLek = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem3.setText("jMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtpStavVeznice.setEditable(false);
        jScrollPane1.setViewportView(jtpStavVeznice);

        jMenu2.setText("Väznica");

        jmivVytvorVeznicu.setText("Vytvor väznicu");
        jmivVytvorVeznicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmivVytvorVeznicuActionPerformed(evt);
            }
        });
        jMenu2.add(jmivVytvorVeznicu);

        jmiKoniec.setText("Koniec");
        jmiKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKoniecActionPerformed(evt);
            }
        });
        jMenu2.add(jmiKoniec);

        jMenuBar1.add(jMenu2);

        jmZamestnaj.setText("Zamestnanec");

        jMenu1.setText("Zamestnaj");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmiZamestnajStraznika.setText("Strážnik");
        jmiZamestnajStraznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiZamestnajStraznikaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiZamestnajStraznika);

        jmiZamestnajLekar.setText("Lekár");
        jmiZamestnajLekar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiZamestnajLekarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiZamestnajLekar);

        jmZamestnaj.add(jMenu1);

        jmiPrepustiZam.setText("Prepusti");
        jmiPrepustiZam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrepustiZamActionPerformed(evt);
            }
        });
        jmZamestnaj.add(jmiPrepustiZam);

        jmiOsetriOsoby.setText("Lekár ošestri osoby");
        jmiOsetriOsoby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOsetriOsobyActionPerformed(evt);
            }
        });
        jmZamestnaj.add(jmiOsetriOsoby);

        jMenu4.setText("Možnosti strážnika");

        jmiOdpracujStraznik.setText("Odpracuj hodiny");
        jmiOdpracujStraznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOdpracujStraznikActionPerformed(evt);
            }
        });
        jMenu4.add(jmiOdpracujStraznik);

        jmZamestnaj.add(jMenu4);

        jMenuBar1.add(jmZamestnaj);

        jmVezen.setText("Väzeň");

        jMenu5.setText("Uväzni");

        jmiUvezniVraha.setText("Vrah");
        jmiUvezniVraha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUvezniVrahaActionPerformed(evt);
            }
        });
        jMenu5.add(jmiUvezniVraha);

        jmiUvezniBankLu.setText("Bankový lupič");
        jmiUvezniBankLu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUvezniBankLuActionPerformed(evt);
            }
        });
        jMenu5.add(jmiUvezniBankLu);

        jmVezen.add(jMenu5);

        jmiPrepustiVezna.setText("Prepusti ");
        jmiPrepustiVezna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrepustiVeznaActionPerformed(evt);
            }
        });
        jmVezen.add(jmiPrepustiVezna);

        jmiZnizStupenNeb.setText("Zníž stupeň nebezpečenstva");
        jmiZnizStupenNeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiZnizStupenNebActionPerformed(evt);
            }
        });
        jmVezen.add(jmiZnizStupenNeb);

        jMenu6.setText("Možnosti bankového lupiča");

        jmiPracujBanLup.setText("Pracuj");
        jmiPracujBanLup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPracujBanLupActionPerformed(evt);
            }
        });
        jMenu6.add(jmiPracujBanLup);

        jmVezen.add(jMenu6);

        jMenu8.setText("Možnosti vraha");

        jmiBitkaSoStraz.setText("Pobi sa so strážnikom");
        jmiBitkaSoStraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBitkaSoStrazActionPerformed(evt);
            }
        });
        jMenu8.add(jmiBitkaSoStraz);

        jmiPridajnavsVrah.setText("Pridaj povolenu navstevu");
        jmiPridajnavsVrah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPridajnavsVrahActionPerformed(evt);
            }
        });
        jMenu8.add(jmiPridajnavsVrah);

        jmiPrijminav.setText("Príjmi/odober navštevu");
        jmiPrijminav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrijminavActionPerformed(evt);
            }
        });
        jMenu8.add(jmiPrijminav);

        jmVezen.add(jMenu8);

        jMenuBar1.add(jmVezen);

        jmVyzbroj.setText("Výzbroj");

        jMenu7.setText("Vlož do muničného skladu");

        jmiVlozgranat.setText("Granát");
        jmiVlozgranat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVlozgranatActionPerformed(evt);
            }
        });
        jMenu7.add(jmiVlozgranat);

        jmiVlozSamopal.setText("Samopal");
        jmiVlozSamopal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVlozSamopalActionPerformed(evt);
            }
        });
        jMenu7.add(jmiVlozSamopal);

        jmVyzbroj.add(jMenu7);

        jmiOdoberZMunSkl.setText("Odober z muničného skladu");
        jmiOdoberZMunSkl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOdoberZMunSklActionPerformed(evt);
            }
        });
        jmVyzbroj.add(jmiOdoberZMunSkl);

        jMenuBar1.add(jmVyzbroj);

        jmUlozDoSuboru.setText("Ulož do súboru");

        jmiUlozCislaNeb.setText("Nebezpečnych väzňov");
        jmiUlozCislaNeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUlozCislaNebActionPerformed(evt);
            }
        });
        jmUlozDoSuboru.add(jmiUlozCislaNeb);

        jmiUlozCisLek.setText("Čísla ubytovaných lekárov");
        jmiUlozCisLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUlozCisLekActionPerformed(evt);
            }
        });
        jmUlozDoSuboru.add(jmiUlozCisLek);

        jMenuBar1.add(jmUlozDoSuboru);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void jmivVytvorVeznicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmivVytvorVeznicuActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        NovaVeznicaDialog dialog = new NovaVeznicaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("StlaceneVytvorVeznicu")).booleanValue()) {
            int maxPocVeznov = ((Integer)preberaneUdaje.get("maximalnyPocetVeznov")).intValue();
            double minZdravStav = ((Double)preberaneUdaje.get("minimalnyZdravotnyStav")).doubleValue();
            int maxPocZamNaPolUv = ((Integer)preberaneUdaje.get("maximalnyPocetZamestnancovNaPolUvazok")).intValue();
            int maxPocUbytLekarov = ((Integer)preberaneUdaje.get("maximalnyPocetUbytLekarov")).intValue();
            int pocAmbulancii = ((Integer)preberaneUdaje.get("pocetAmbulancii")).intValue();
            int maxPocGranatov = ((Integer)preberaneUdaje.get("maximalnyPocetGranatov")).intValue();
            int financneProstriedky = ((Integer)preberaneUdaje.get("financneProstriedky")).intValue();
            
            this.veznica = new Veznica(maxPocVeznov, minZdravStav, financneProstriedky, maxPocGranatov, maxPocZamNaPolUv, maxPocUbytLekarov, pocAmbulancii);
            this.jtpStavVeznice.setText(this.veznica.toString());
            
            this.jmivVytvorVeznicu.setEnabled(false);
            this.jmZamestnaj.setEnabled(true);
            this.jmVezen.setEnabled(true);
            this.jmVyzbroj.setEnabled(true);
            this.jmUlozDoSuboru.setEnabled(true);
        }
    }//GEN-LAST:event_jmivVytvorVeznicuActionPerformed

    private void jmiKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKoniecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiKoniecActionPerformed

    private void jmiZamestnajStraznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiZamestnajStraznikaActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        ZamestnajStraznikaDialog dialog = new ZamestnajStraznikaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneZamestnajStraznika")).booleanValue()) {
            String idenCislo = ((String)preberaneUdaje.get("identifikacneCislo"));
            int pocRokPraxe = ((Integer)preberaneUdaje.get("pocetRokovPraxe")).intValue();
            Hodnost hodnost = ((Hodnost)preberaneUdaje.get("hodnost"));
            TypZamestnania tZam = ((TypZamestnania)preberaneUdaje.get("typZamestnania"));
            
            this.veznica.zamestnajStraznikaDoCely(hodnost, tZam, idenCislo, pocRokPraxe);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
    }//GEN-LAST:event_jmiZamestnajStraznikaActionPerformed

    private void jmiUvezniBankLuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUvezniBankLuActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        UvezniBankovehoLupicaDialog dialog = new UvezniBankovehoLupicaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("StlaceneUvezniBankLuppica")).booleanValue()) {
            String cisloBankLup = (String)preberaneUdaje.get("cisloVezna");
            int pocRokOds = ((Integer)preberaneUdaje.get("pocetRokovOdsudenia")).intValue();
            double zdravStav = ((Double)preberaneUdaje.get("zdravotnyStav")).doubleValue();
            int pocPovVych = ((Integer)preberaneUdaje.get("pocetPovolenychVych")).intValue();
            StupenNebezpecenstva stNe = ((StupenNebezpecenstva)preberaneUdaje.get("stupenNebezpecenstva"));
            double ukrCias = ((Double)preberaneUdaje.get("ukradnutaCiastka")).doubleValue();
            
            this.veznica.uvezniBankovehoLupica(ukrCias, pocPovVych, cisloBankLup, pocRokOds, stNe, zdravStav);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
    }//GEN-LAST:event_jmiUvezniBankLuActionPerformed

    private void jmiUvezniVrahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUvezniVrahaActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        UvezniVrahaDialog dialog = new UvezniVrahaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("StlaceneUvezniVraha")).booleanValue()) {
            String cisloVraha = (String)preberaneUdaje.get("cisloVezna");
            int pocRokOds = ((Integer)preberaneUdaje.get("pocetRokovOdsudenia")).intValue();
            double zdravStav = ((Double)preberaneUdaje.get("zdravotnyStav")).doubleValue();
            int pocPovNavs = ((Integer)preberaneUdaje.get("pocetPovolenychNavstev")).intValue();
            StupenNebezpecenstva stNe = ((StupenNebezpecenstva)preberaneUdaje.get("stupenNebezpecenstva"));
            
            this.veznica.uvezniVrahaDoCely(pocPovNavs, cisloVraha, pocRokOds, stNe, zdravStav);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
        
        
    }//GEN-LAST:event_jmiUvezniVrahaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmiZamestnajLekarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiZamestnajLekarActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        ZamestnajLekaraDialog dialog = new ZamestnajLekaraDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneZamestnajLekara")).booleanValue()) {
            String idenCislo = ((String)preberaneUdaje.get("identifikacneCislo"));
            int pocRokPraxe = ((Integer)preberaneUdaje.get("pocetRokovPraxe")).intValue();
            TypZamestnania tZam = ((TypZamestnania)preberaneUdaje.get("typZamestnania"));
            int vzdialenost = ((Integer)preberaneUdaje.get("vzdialenost")).intValue();
            
            this.veznica.zamestnajLekaraVStraznejVezi(tZam, idenCislo, pocRokPraxe, vzdialenost);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
    }//GEN-LAST:event_jmiZamestnajLekarActionPerformed

    private void jmiVlozgranatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVlozgranatActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        VlozGranatDialog dialog = new VlozGranatDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneVlozGranat")).booleanValue()) {
            String serioveCislo = (String)preberaneUdaje.get("serioveCislo");
            double cena = ((Double)preberaneUdaje.get("cena")).doubleValue();
            double hmotnost = ((Double)preberaneUdaje.get("hmotnost")).doubleValue();
            
            this.veznica.vlozGranatDoMunicnehoSkladu(serioveCislo, cena, hmotnost);
            this.jtpStavVeznice.setText(this.veznica.toString());
            
        }
    }//GEN-LAST:event_jmiVlozgranatActionPerformed

    private void jmiVlozSamopalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVlozSamopalActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        VlozSamopalDialog dialog = new VlozSamopalDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneVlozSamopal")).booleanValue()) {
            String serioveCislo = (String)preberaneUdaje.get("serioveCislo");
            double cena = ((Double)preberaneUdaje.get("cena")).doubleValue();
            int kapacitaZas = ((Integer)preberaneUdaje.get("kapacitaZasobnika")).intValue();
            this.veznica.vlozSamopalDoMunicnehoSkladu(kapacitaZas, serioveCislo, cena);
            this.jtpStavVeznice.setText(this.veznica.toString());
        } 
    }//GEN-LAST:event_jmiVlozSamopalActionPerformed

    private void jmiPrepustiZamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrepustiZamActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        PrepustiZamestnancaDialog dialog = new PrepustiZamestnancaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String idenCi = (String)preberaneUdaje.get("identifikacneCislo");
            this.veznica.prepustiZamestnancaZoStraznejVezi(idenCi);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
        
    }//GEN-LAST:event_jmiPrepustiZamActionPerformed

    private void jmiPrepustiVeznaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrepustiVeznaActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        PrepustiVeznaDialog dialog = new PrepustiVeznaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String cisloVezna = (String)preberaneUdaje.get("cisloVezna");
            this.veznica.prepustiVeznaZCely(cisloVezna);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
    }//GEN-LAST:event_jmiPrepustiVeznaActionPerformed

    private void jmiOdoberZMunSklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOdoberZMunSklActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        OdoberVyzbrojDialog dialog = new OdoberVyzbrojDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String serioveCislo = (String)preberaneUdaje.get("serioveCislo");
            this.veznica.odoberVyzbrojZMunicnehoSkladu(serioveCislo);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
    }//GEN-LAST:event_jmiOdoberZMunSklActionPerformed

    private void jmiPracujBanLupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPracujBanLupActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        PracujBankovyLupicDialog dialog = new PracujBankovyLupicDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String cisloBanLup = (String)preberaneUdaje.get("cisloBanLup");
            int pocOdpracHod = ((Integer)preberaneUdaje.get("pocOdpracHod")).intValue();
            this.veznica.pracujBankovyLupic(cisloBanLup, pocOdpracHod);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }    
        
        
    }//GEN-LAST:event_jmiPracujBanLupActionPerformed

    private void jmiUlozCislaNebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUlozCislaNebActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        UlozDoSuboruDialog dialog = new UlozDoSuboruDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String nazovSuboru = (String)preberaneUdaje.get("nazovSuboru");
            if(this.veznica.ulozDoSuboruNebezpecnychVeznov(nazovSuboru)) {
                JOptionPane.showMessageDialog(this, "Súbor úspešne uložený");
            }
        }
    }//GEN-LAST:event_jmiUlozCislaNebActionPerformed

    private void jmiUlozCisLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUlozCisLekActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        UlozDoSuboruDialog dialog = new UlozDoSuboruDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String nazovSuboru = (String)preberaneUdaje.get("nazovSuboru");
            if(this.veznica.ulozDoSuboruCislaUbytLekarov(nazovSuboru)) {
                JOptionPane.showMessageDialog(this, "Súbor úspešne uložený");
            }
        }
    }//GEN-LAST:event_jmiUlozCisLekActionPerformed

    private void jmiZnizStupenNebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiZnizStupenNebActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        PrepustiVeznaDialog dialog = new PrepustiVeznaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String cisloVezna = (String)preberaneUdaje.get("cisloVezna");
            
            if (this.veznica.znizStupenNebezpecenstva(cisloVezna)) {
                JOptionPane.showMessageDialog(this, "Stupen uspesne znizeny");
            } else {
                JOptionPane.showMessageDialog(this, "Stupen sa viac neda znizit");
            }
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
    }//GEN-LAST:event_jmiZnizStupenNebActionPerformed

    private void jmiBitkaSoStrazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBitkaSoStrazActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        PrepustiVeznaDialog dialog = new PrepustiVeznaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String cisloVezna = (String)preberaneUdaje.get("cisloVezna");
            this.veznica.pobiSaSoStraznikomVrah(cisloVezna);
            JOptionPane.showMessageDialog(this, "Vrah sa pobil so straznikom a tak sa jeho zdravotny stav zhorsil a bol mu udeleny trest");
            this.jtpStavVeznice.setText(this.veznica.toString());

        }
    }//GEN-LAST:event_jmiBitkaSoStrazActionPerformed

    private void jmiOsetriOsobyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOsetriOsobyActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        OstetriOsobyDialog dialog = new OstetriOsobyDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String cisloLekara = (String)preberaneUdaje.get("cisloLekara");
            int pocOsetOsob = ((Integer)preberaneUdaje.get("pocetOsetrenychOsob")).intValue();
            this.veznica.osetriOsobyLekar(cisloLekara, pocOsetOsob);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
    }//GEN-LAST:event_jmiOsetriOsobyActionPerformed

    private void jmiOdpracujStraznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOdpracujStraznikActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        PocOdpracovanychHodStraznikDialog dialog = new PocOdpracovanychHodStraznikDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String cisloStraznika = (String)preberaneUdaje.get("cisloStraznika");
            int pocOdpracHod = ((Integer)preberaneUdaje.get("pocetOdpracHod")).intValue();
            this.veznica.pridajHodinyPraceStraznik(cisloStraznika, pocOdpracHod);
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
    }//GEN-LAST:event_jmiOdpracujStraznikActionPerformed

    private void jmiPridajnavsVrahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPridajnavsVrahActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        PrepustiVeznaDialog dialog = new PrepustiVeznaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String cisloVezna = (String)preberaneUdaje.get("cisloVezna");
            if (this.veznica.pridajPovolenuNavstevuVrahovi(cisloVezna)) {
                JOptionPane.showMessageDialog(this, "Vrahovi bola pridana jedna povolena navsteva");
            } else {
                JOptionPane.showMessageDialog(this, "Tomuto vrahovi sa neda pridat povolena navsteva");
            }
            this.jtpStavVeznice.setText(this.veznica.toString());
        }
    }//GEN-LAST:event_jmiPridajnavsVrahActionPerformed

    private void jmiPrijminavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrijminavActionPerformed
        HashMap<String, Object> preberaneUdaje = new HashMap<>();
        
        PrepustiVeznaDialog dialog = new PrepustiVeznaDialog(GUIAplikacia.this, true, preberaneUdaje);
        dialog.setVisible(true);
        if (((Boolean)preberaneUdaje.get("stlaceneOk")).booleanValue()) {
            String cisloVezna = (String)preberaneUdaje.get("cisloVezna");
            if (this.veznica.prijmiNavstevuVrah(cisloVezna)) {
                JOptionPane.showMessageDialog(this, "Vrah prijal navstevu");
            } else {
                JOptionPane.showMessageDialog(this, "Tento vrah nemoze prijat navstevu");
            }
            this.jtpStavVeznice.setText(this.veznica.toString());
        
        }
    }//GEN-LAST:event_jmiPrijminavActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAplikacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAplikacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAplikacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAplikacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAplikacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmUlozDoSuboru;
    private javax.swing.JMenu jmVezen;
    private javax.swing.JMenu jmVyzbroj;
    private javax.swing.JMenu jmZamestnaj;
    private javax.swing.JMenuItem jmiBitkaSoStraz;
    private javax.swing.JMenuItem jmiKoniec;
    private javax.swing.JMenuItem jmiOdoberZMunSkl;
    private javax.swing.JMenuItem jmiOdpracujStraznik;
    private javax.swing.JMenuItem jmiOsetriOsoby;
    private javax.swing.JMenuItem jmiPracujBanLup;
    private javax.swing.JMenuItem jmiPrepustiVezna;
    private javax.swing.JMenuItem jmiPrepustiZam;
    private javax.swing.JMenuItem jmiPridajnavsVrah;
    private javax.swing.JMenuItem jmiPrijminav;
    private javax.swing.JMenuItem jmiUlozCisLek;
    private javax.swing.JMenuItem jmiUlozCislaNeb;
    private javax.swing.JMenuItem jmiUvezniBankLu;
    private javax.swing.JMenuItem jmiUvezniVraha;
    private javax.swing.JMenuItem jmiVlozSamopal;
    private javax.swing.JMenuItem jmiVlozgranat;
    private javax.swing.JMenuItem jmiZamestnajLekar;
    private javax.swing.JMenuItem jmiZamestnajStraznika;
    private javax.swing.JMenuItem jmiZnizStupenNeb;
    private javax.swing.JMenuItem jmivVytvorVeznicu;
    private javax.swing.JTextPane jtpStavVeznice;
    // End of variables declaration//GEN-END:variables
}
