package dialogy;

import java.util.HashMap;
import javax.swing.JDialog;


/**
 *
 * @author dominik
 */
public class NovaVeznicaDialog extends javax.swing.JDialog {
    private HashMap<String, Object> preberaneUdaje;
    private JDialog dialog;
    
    public NovaVeznicaDialog(java.awt.Frame parent, boolean modal, HashMap<String,Object> preberaneUdaje) {
        super(parent, modal);
        initComponents();
        this.dialog = this;
        this.preberaneUdaje = preberaneUdaje;
        this.preberaneUdaje.put("StlaceneVytvorVeznicu", new Boolean(false));
        this.jcmxMinZdravStav.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxfMaxPocVeznov = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxfMaxPocZamNaPolUvazok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxPocetAmbulancii = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxMaxPocUbytLekarov = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxFinancneProstriedky = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxMaxPocGranatov = new javax.swing.JTextField();
        jbtnVytvorVeznicu = new javax.swing.JButton();
        jcmxMinZdravStav = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Väznica");
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(20, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cela:");

        jLabel2.setText("Maximalny počet väzňov:");

        jLabel3.setText("Minimalny zdravotný stav väzňov [%]:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Strážna veža:");

        jLabel5.setText("Max. počet zamest. na polovičný úväzok:");
        jLabel5.setToolTipText("");
        jLabel5.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabel6.setText("Počet ambulancii:");

        jLabel7.setText("Maximalny počet ubytovanych lekarov:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Muničný sklad:");

        jLabel9.setText("Finančné prostriedky [€]:");

        jLabel10.setText("Maximalny počet granátov:");

        jbtnVytvorVeznicu.setText("Vytvor väznicu");
        jbtnVytvorVeznicu.addActionListener(evt -> jbtnVytvorVeznicuActionPerformed(evt));

        jcmxMinZdravStav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "40", "30", "20", "10" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxfMaxPocZamNaPolUvazok)
                    .addComponent(jtxfMaxPocVeznov)
                    .addComponent(jLabel6)
                    .addComponent(jtxPocetAmbulancii)
                    .addComponent(jLabel7)
                    .addComponent(jtxMaxPocUbytLekarov)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jtxFinancneProstriedky)
                    .addComponent(jLabel10)
                    .addComponent(jtxMaxPocGranatov)
                    .addComponent(jbtnVytvorVeznicu)
                    .addComponent(jcmxMinZdravStav, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxfMaxPocVeznov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcmxMinZdravStav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxfMaxPocZamNaPolUvazok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxPocetAmbulancii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxMaxPocUbytLekarov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxFinancneProstriedky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxMaxPocGranatov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnVytvorVeznicu)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVytvorVeznicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVytvorVeznicuActionPerformed
        this.preberaneUdaje.put("StlaceneVytvorVeznicu", new Boolean(true));
        this.preberaneUdaje.put("maximalnyPocetVeznov", Integer.parseInt(this.jtxfMaxPocVeznov.getText()));
        this.preberaneUdaje.put("minimalnyZdravotnyStav", Double.parseDouble((String)this.jcmxMinZdravStav.getSelectedItem()));
        this.preberaneUdaje.put("maximalnyPocetZamestnancovNaPolUvazok", Integer.parseInt(this.jtxfMaxPocZamNaPolUvazok.getText()));
        this.preberaneUdaje.put("maximalnyPocetUbytLekarov", Integer.parseInt(this.jtxMaxPocUbytLekarov.getText()));
        this.preberaneUdaje.put("financneProstriedky", Integer.parseInt(this.jtxFinancneProstriedky.getText()));
        this.preberaneUdaje.put("maximalnyPocetGranatov", Integer.parseInt(this.jtxMaxPocGranatov.getText()));
        this.preberaneUdaje.put("pocetAmbulancii", Integer.parseInt(this.jtxPocetAmbulancii.getText()));
        this.dialog.setVisible(false);
    }//GEN-LAST:event_jbtnVytvorVeznicuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaVeznicaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaVeznicaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaVeznicaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaVeznicaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovaVeznicaDialog dialog = new NovaVeznicaDialog(new javax.swing.JFrame(), true, new HashMap<String, Object>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnVytvorVeznicu;
    private javax.swing.JComboBox<String> jcmxMinZdravStav;
    private javax.swing.JTextField jtxFinancneProstriedky;
    private javax.swing.JTextField jtxMaxPocGranatov;
    private javax.swing.JTextField jtxMaxPocUbytLekarov;
    private javax.swing.JTextField jtxPocetAmbulancii;
    private javax.swing.JTextField jtxfMaxPocVeznov;
    private javax.swing.JTextField jtxfMaxPocZamNaPolUvazok;
    // End of variables declaration//GEN-END:variables
}
