/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogy;

import javax.swing.JDialog;
import java.util.HashMap;
import vaznica.objektyvaznice.Hodnost;
import vaznica.objektyvaznice.TypZamestnania;

/**
 *
 * @author dominik
 */
public class ZamestnajStraznikaDialog extends javax.swing.JDialog {
    private JDialog dialog;
    private HashMap<String , Object> preberaneUdaje;        
    
    public ZamestnajStraznikaDialog(java.awt.Frame parent, boolean modal, HashMap<String,Object>preberaneUdaje) {
        super(parent, modal);
        initComponents();
        this.preberaneUdaje = preberaneUdaje;
        this.dialog = this;
        this.btngHodnost.add(this.jrbtKapitan);
        this.btngHodnost.add(this.jrbtPorucik);
        this.btngTypZam.add(this.jrbtPolUvazok);
        this.btngTypZam.add(this.jrbtPlnyUvazok);
        this.preberaneUdaje.put("stlaceneZamestnajStraznika", new Boolean(false));
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTypZam = new javax.swing.ButtonGroup();
        btngHodnost = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxfidenCislo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrbtPlnyUvazok = new javax.swing.JRadioButton();
        jrbtPolUvazok = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jrbtKapitan = new javax.swing.JRadioButton();
        jrbtPorucik = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jtxfPocRokovPraxe = new javax.swing.JTextField();
        jbtZamestnajStraznika = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Strážnik:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Identifikačné čislo:");

        jtxfidenCislo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfidenCisloActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Typ zamestnania:");

        btngTypZam.add(jrbtPlnyUvazok);
        jrbtPlnyUvazok.setText("Plný uväzok");

        btngTypZam.add(jrbtPolUvazok);
        jrbtPolUvazok.setText("Polovičný uväzok");
        jrbtPolUvazok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtPolUvazokActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Hodnosť:");

        btngHodnost.add(jrbtKapitan);
        jrbtKapitan.setText("Kapitán");

        btngHodnost.add(jrbtPorucik);
        jrbtPorucik.setText("Poručík");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Počet rokov praxe:");

        jbtZamestnajStraznika.setText("Zamestnaj strážnika");
        jbtZamestnajStraznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtZamestnajStraznikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jtxfidenCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jtxfPocRokovPraxe)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jrbtPlnyUvazok)
                                .addComponent(jrbtKapitan))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jrbtPorucik)
                                .addComponent(jrbtPolUvazok))))
                    .addComponent(jbtZamestnajStraznika))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxfidenCislo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtPlnyUvazok)
                    .addComponent(jrbtPolUvazok))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtKapitan)
                    .addComponent(jrbtPorucik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxfPocRokovPraxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtZamestnajStraznika)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxfidenCisloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfidenCisloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxfidenCisloActionPerformed

    private void jrbtPolUvazokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtPolUvazokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtPolUvazokActionPerformed

    private void jbtZamestnajStraznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtZamestnajStraznikaActionPerformed
        Hodnost hodnost = null;
        TypZamestnania tZam = null;
        this.preberaneUdaje.put("stlaceneZamestnajStraznika", new Boolean(true));
        this.preberaneUdaje.put("identifikacneCislo", this.jtxfidenCislo.getText());
        this.preberaneUdaje.put("pocetRokovPraxe", Integer.parseInt(this.jtxfPocRokovPraxe.getText()));
        
        if (this.jrbtKapitan.isSelected()) {
            hodnost = Hodnost.KAPITAN;
        } 
        if (this.jrbtPorucik.isSelected()) {
            hodnost = Hodnost.PORUCIK;
        }
        this.preberaneUdaje.put("hodnost", hodnost);
        
        if (this.jrbtPlnyUvazok.isSelected()) {
            tZam = TypZamestnania.PLNYUVAZOK;
        }
        if (this.jrbtPolUvazok.isSelected()) {
            tZam = TypZamestnania.POLOVICNYUVAZOK;
        }
        this.preberaneUdaje.put("typZamestnania", tZam);
        
        this.dialog.setVisible(false);
        
    }//GEN-LAST:event_jbtZamestnajStraznikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZamestnajStraznikaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZamestnajStraznikaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZamestnajStraznikaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZamestnajStraznikaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ZamestnajStraznikaDialog dialog = new ZamestnajStraznikaDialog(new javax.swing.JFrame(), true, new HashMap<String, Object>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngHodnost;
    private javax.swing.ButtonGroup btngTypZam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtZamestnajStraznika;
    private javax.swing.JRadioButton jrbtKapitan;
    private javax.swing.JRadioButton jrbtPlnyUvazok;
    private javax.swing.JRadioButton jrbtPolUvazok;
    private javax.swing.JRadioButton jrbtPorucik;
    private javax.swing.JTextField jtxfPocRokovPraxe;
    private javax.swing.JTextField jtxfidenCislo;
    // End of variables declaration//GEN-END:variables
}
