/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogy;

import javax.swing.JDialog;
import java.util.HashMap;
import vaznica.objektyvaznice.Hodnost;
import vaznica.objektyvaznice.TypZamestnania;
/**
 *
 * @author dominik
 */
public class ZamestnajLekaraDialog extends javax.swing.JDialog {
    private JDialog dialog;
    private HashMap<String , Object> preberaneUdaje;  
    
    public ZamestnajLekaraDialog(java.awt.Frame parent, boolean modal, HashMap<String,Object>preberaneUdaje) {
        super(parent, modal);
        initComponents();
        this.preberaneUdaje = preberaneUdaje;
        this.dialog = this;
        this.btngTypZam.add(this.hrbtnPolUv);
        this.btngTypZam.add(this.jrbtnPlnyUv);
        this.preberaneUdaje.put("stlaceneZamestnajLekara", new Boolean(false));
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTypZam = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxfidenCislo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jrbtnPlnyUv = new javax.swing.JRadioButton();
        hrbtnPolUv = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jtxfPocRokPraxe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxfVzdialOdBydliska = new javax.swing.JTextField();
        jbtnZamestnajLekara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Lekár:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Identifikačné číslo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Typ zamestnania:");

        btngTypZam.add(jrbtnPlnyUv);
        jrbtnPlnyUv.setText("Plný úväzok");

        btngTypZam.add(hrbtnPolUv);
        hrbtnPolUv.setText("Polovičný úväzok");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Počet rokov praxe:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Vzdialenosť bydliska od väznice [km]:");

        jbtnZamestnajLekara.setText("Zamestnaj lekára");
        jbtnZamestnajLekara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZamestnajLekaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxfPocRokPraxe)
                    .addComponent(jtxfidenCislo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jrbtnPlnyUv)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hrbtnPolUv))
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxfVzdialOdBydliska))
                            .addComponent(jbtnZamestnajLekara))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxfidenCislo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtnPlnyUv)
                    .addComponent(hrbtnPolUv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxfPocRokPraxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxfVzdialOdBydliska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnZamestnajLekara)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnZamestnajLekaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZamestnajLekaraActionPerformed
        TypZamestnania tZam = null;
        this.preberaneUdaje.put("stlaceneZamestnajLekara", new Boolean(true));
        this.preberaneUdaje.put("identifikacneCislo", this.jtxfidenCislo.getText());
        this.preberaneUdaje.put("pocetRokovPraxe", Integer.parseInt(this.jtxfPocRokPraxe.getText()));
        this.preberaneUdaje.put("vzdialenost", Integer.parseInt(this.jtxfVzdialOdBydliska.getText()));
        if (this.hrbtnPolUv.isSelected()) {
            tZam = TypZamestnania.PLNYUVAZOK;
        }
        
        if (this.jrbtnPlnyUv.isSelected()) {
            tZam = TypZamestnania.PLNYUVAZOK;
        }
        
            
        this.preberaneUdaje.put("typZamestnania", tZam);
        
        this.dialog.setVisible(false);
    }//GEN-LAST:event_jbtnZamestnajLekaraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZamestnajLekaraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZamestnajLekaraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZamestnajLekaraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZamestnajLekaraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ZamestnajLekaraDialog dialog = new ZamestnajLekaraDialog(new javax.swing.JFrame(), true, new HashMap<String, Object>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngTypZam;
    private javax.swing.JRadioButton hrbtnPolUv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnZamestnajLekara;
    private javax.swing.JRadioButton jrbtnPlnyUv;
    private javax.swing.JTextField jtxfPocRokPraxe;
    private javax.swing.JTextField jtxfVzdialOdBydliska;
    private javax.swing.JTextField jtxfidenCislo;
    // End of variables declaration//GEN-END:variables
}
